### PR TITLE
Navigator missing in rng.js file

### PR DESCRIPTION
**Pull request by venomdev**
This fixes the navigator missing in the rng.js file

you may only need this commit:
[c6fcf2c271a779bb32f665031f6a82c866cbcecc](https://github.com/nikvdp/pidcrypt/commit/c6fcf2c271a779bb32f665031f6a82c866cbcecc)

### CODE REVIEW

**Comment by nikvdp** [comment]
nice, thanks!

**Comment by venomdev** [comment]
No worries, just for the record it's not my fix. Credit to [Anton Marsden](https://github.com/antonmarsden)

Can you bump the version and release on npm please?

I have a library that relies on pidcrypt that is failing atm.

**Comment by nikvdp** [comment]
@venomdev you bet, just published 0.0.33

**Comment by venomdev** [comment]
Thanks, much appreciated.

**Pull request merged**
